### ISSUE TITLE
lunchdev overlay

### ISSUE THREAD

**Issue by chantastic** [BenDMyers/showmy.chat#10]
Hey!

I'm really excited to contribute an overlay. I thought I'd create an issue with my notes from each stream. And then knock them all out at once.

- extend: `cards` theme
- add customizable background key color to improve white:white overlays (screenshot attached)
- add timeout so cards disappear automatically
- use (working) brand font [Rubik](https://fonts.google.com/specimen/Rubik#standard-styles)

*white:white* de-focused cards screenshot
<img width="247" alt="image" src="https://user-images.githubusercontent.com/658360/137984838-9d0ea1b4-1885-475e-9705-1632023bd05f.png">

**Comment by BenDMyers** [comment]
Closing to clean up our issues list a bit
