### ISSUE TITLE
Bug: long links are causing scrollbars on the default theme

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [BenDMyers/showmy.chat#158]
Thanks so much for making this service! It's working great for me! 💖 

One note: long links in the chat are causing a horizontal scrollbar instead of overflowing to the next line. Is this a bug?

![Screenshot of the default theme in OBS as a browser source with long links causing a horizontal overflow scrollbar in Windows](https://user-images.githubusercontent.com/3335181/173663779-6c685c1c-3a3d-4d5b-ab75-2bd31c6fd679.png)

**Comment by BenDMyers** [comment]
[Possibly helpful resource on wrapping text with CSS.](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/) Ideally, wrapping will behave as naturally when possible, and mid-word breaks should only happen for really long URLs/words.
