### ISSUE TITLE
Create a `defaults.css` file for commonly used css for each theme

### ISSUE THREAD

**Issue by fimion** [BenDMyers/showmy.chat#44]
This would include setting certain overflow styles, document height, etc

**Comment by BenDMyers** [comment]
I love this idea. I'm not totally sure how far to take it, though. Do we include just the bare minimum that most if not all themes are already using? (for instance, the boilerplate `[data-twitch-chat]` styles?), or do we go full Normalize.css? I'm curious what would be the most helpful here.

One thing I'm keen about making sure is that we have a good strategy for safely updating the contents of `defaults.css` without causing a lot of downstream changes to themes.

**Comment by BenDMyers** [comment]
Resolved in 2f47210db5c7dfcb36c164bc9463d7d048523499
