### ISSUE TITLE
🚨 Security Concern ⚠Credentials are being shown on twitch websocket that's used for the array passed into formatEmotes()

### ISSUE THREAD

**Issue by KenAKAFrosty** [BenDMyers/showmy.chat#45]

**Comment by BenDMyers** [comment]
Can you specify whose credentials are being shown, and what credentials those are?

showmychat doesn't use any authentication, and all this info is coming from Comfy, and tmi.JS in turn, so if something is getting exposed, I think it's an upstream problem.

**Comment by BenDMyers** [comment]
Closing for now, as it appears that this is the dummy credentials Comfy/tmi.js generates in the absence of authentication. There very well might be some leakage, but this would be upstream in Comfy or tmi.js. For now especially, we don't anticipate that anyone would authenticate their chat for this to be a concern.
