### ISSUE TITLE
Deletion of messages after banning the author is not being reflected

### ISSUE THREAD

**Issue by hwanders** [BenDMyers/showmy.chat#48]
When a user first gets banned and then their message gets deleted, the chat view does update accordingly: the deleted message persists.

### Expected behavior
A deleted message should be removed from the chat view, even if its author has been banned before.

### Additional info
According to @BenDMyers, first deleting the message (and then banning the user) works fine.
Observed during maxcellw's twitch stream.

**Comment by BenDMyers** [comment]
What makes this tricky is, from what I can tell, banning a commenter for their message within Twitch doesn't seem to fire the `onMessageDeleted` event (or maybe it does and there's an error somewhere?)

Anyways, if there's any way to delete the message when the user is banned, we should do so, as it breaks users' assumption that "deleting" the message will delete it in the overlay view, too.

**Comment by KenAKAFrosty** [comment]
Looked closer at Comfy. I have a hunch we could check onPart event for user metadata, since banning would force them to leave. There may be some sort of boolean flag on the user for 'banned' or similar? Then if so, delete all messages with a matching sender username

**Comment by BenDMyers** [comment]
I think this issue (still open, at time of writing) on the ComfyJS repo could be helpful: instafluff/ComfyJS#23 — it seems like the tmi.js client does expose a `'ban'` event, but ComfyJS isn't yet consuming it.

I think maybe the best path forward for this issue could be contributing an `onBan` hook to ComfyJS that we could leverage here?

**Comment by KenAKAFrosty** [comment]
Perfect! I had half a mind to see if it was Comfy not exposing tmi
functionality and here you've already dug into that very thing and even
found a current issue! Id love to work with you to go contribute to Comfy
(plus even if it takes time to get a PR merged, we could still use it in
this codebase in the interim)

**Comment by BenDMyers** [comment]
@KenAKAFrosty Would you be able to look into adding the `onBan` hook upstream in ComfyJS?
