### ISSUE TITLE
Allow users to bring their own styles

### ISSUE THREAD

**Issue by NickyMeuleman** [BenDMyers/showmy.chat#78]
Allow users to provide their own CSS.
That way they can either tweak a theme to their liking, or even use it to bring their own custom theme. (maybe this can be used to build custom themes on a base of #44)

This raises a few security questions.
It would mean executing CSS on the user's device.
While CSS is _probably_ fine, executing _any_ code that can be user-supplied warrants a closer look at how that is handled.

**Comment by BenDMyers** [comment]
Hey, @NickyMeuleman! Can you let me know what you're imagining this experience to be like?

**Comment by NickyMeuleman** [comment]
I was thinking about an optional way to load a (local) .css file.
That way you could use showmy.chat without having to stick strictly to the pre-defined themes.

This wouldn't replace the pre-defined themes, but be an optional way to provide CSS selectors and supply additions/overrides.

Not sure how that would work yet.
We may be able to provide another queryparam that does this.
Like how the correct theme .css file is chosen now, also add a (local) one if it is supplied.

**Comment by BenDMyers** [comment]
Gotcha — I thiiiiink this is already supported, through other routes.

If you want to start with a theme and just tweak styles, OBS (and maybe OBS's descendants?) let you inject custom styles into your browser source.

If you'd like to inject a whole dang stylesheet, the `theme` attribute does support a valid URI. I haven't really tested it with local files, but I have confirmed that it supports any stylesheets hosted publicly and served with the `text/css` MIME type? (Unfortunately, GitHub's raw viewer serves even stylesheets as `text/plain`). It'd be worth validating whether this already supports local filepaths out of the box.

**Comment by NickyMeuleman** [comment]
Nice! Didn't know that.
Just tried to load a local file really quick (with some minor changes to the sourcode) and it seems browsers block this for security reasons.
The method I tried was using a 	file:// URI.
I tested `http://localhost:8080/c/test?DEMO=true&theme=file://home/nicky/projects/showmy.chat/src/test.css` and the browser blocked it.

Since using local CSS is possible via the tools you're likely to use showmy.chat with like OBS this is fine.
(OBS worked perfectly, really nice)

Didn't test the web-hosted files yet.
If that works, feel free to close this issue!

**Comment by BenDMyers** [comment]
Here's an example of using [Pico.css](https://picocss.com/) as an external, CDN-hosted stylesheet:

<https://showmy.chat/c/NMeuleman?DEMO=true&theme=https://unpkg.com/@picocss/pico@latest/css/pico.min.css>

**Comment by BenDMyers** [comment]
There's a brief comment about this feature in the config docs — <https://showmy.chat/docs/configuration/#theme> — but it's easy to miss. I think this feature is very cool because not only does it mean folks can build their own themes without having to go through the contributor workflow, it also allows us to provide _private_ themes for folks (and have them be responsible for hosting).

**Comment by NickyMeuleman** [comment]
It's awesome and was exactly what I was thinking of when I created this issue!
