### ISSUE TITLE
Create a guide for integrating with OBS

### ISSUE THREAD

**Issue by alexanderson1993** [BenDMyers/showmy.chat#90]
There are a lot of folks who want to get into streaming and have fancy overlays, like showmy.chat, but they don't actually know how to make it work with OBS.

Like, there's this website thing? And I can configure it, and it loads stuff from my Twitch - that's cool. But how do I actually get that overlay into my stream?

It would be awesome if there were a guide somewhere that explains what the Browser source is, how it works, how to configure it showmy.chat, where to position it in the sources layers, etc. etc. I think that would be beneficial for getting beginners who don't really know where to start... started.

**Comment by Harsh97x** [comment]
Do you want a step-by-step guide with pictures or just the steps written down in a doc?
