### ISSUE TITLE
Testing Discord webhook; please disregard.

### ISSUE THREAD

**Issue by BenDMyers** [BenDMyers/showmy.chat#93]
I'm adding a webhook to the Discord server that'll notify the `#github` channel of activity on this repo. This is a test.

**Comment by ajcwebdev** [comment]
![test-homer-simpson](https://user-images.githubusercontent.com/12433465/155427886-ad287f12-02da-4f98-b732-ad72fd6706bc.gif)

**Comment by BenDMyers** [comment]
Seems to work like a charm! Thank you for your validation, @ajcwebdev!
